== Getting started modules

Welcome to Getting started! If you are a complete beginner (i.e., you’ve
not installed a code editor or written any code yet), then this is the
place to be. The Getting started modules take you through installing the
software you need, familiarity with your development environment, taking
your first stab at building a simple website, and understanding some of
the essential concepts surrounding web development.

=== In this article

* Prerequisites
* Modules
* See also
* Prerequisites *There is no prerequisite knowledge for starting this
course.* Also note that we don’t consider learning these topics as
required before moving on to the Core modules, ++>++ but we believe
students will have an easier time if they spend some time on these
topics first.

==== Modules

_Environment setup_ In the Environment setup module, we show you what
tools you need to do simple web development and how to install them
properly and help you understand important aspects of your environment
such as file systems and the command line.

===== Your first website

*This module introduces you to the practicalities of web development.*
You’ll gather the assets and write the code to construct and publish a
simple webpage.

==== Web standards

This module covers the fundamentals of how the web works at a high level
— including the model used for communication, the core technologies
involved, how those technologies are created, and how a web browser
renders and displays websites to a user.

Soft skills This module provides recommendations of soft skills you can
aim to get better at while learning web development, and which
constitute good traits to have when entering the industry. They will
help immensely in developing the right attitudes for learning,
researching, and collaborating, and increase the chances of getting
hired.

===== See also

The Frontend Developer Career Path MDN learning partner Scrimba’s
Frontend Developer Career Path teaches all you need to know to be a
competent front-end web developer, with fun interactive lessons and
challenges, knowledgeable teachers, and a supportive community. Go from
zero to landing your first front-end job! Many of the course components
are available as standalone free versions. _Getting started modules_
Welcome to Getting started! If you are a complete beginner (i.e., you’ve
not installed a code editor or written any code yet), then this is the
place to be. The Getting started modules take you through installing the
software you need, familiarity with your development environment, taking
your first stab at building a simple website, and understanding some of
the essential concepts surrounding web development.

*In this article* 1. Prerequisites 2. Modules 3. See also 4.
Prerequisites There is no prerequisite knowledge for starting this
course. Also note that we don’t consider learning these topics as
required before moving on to the Core modules, but we believe students
will have an easier time if they spend some time on these topics first.

Modules Environment setup In the Environment setup module, we show you
what tools you need to do simple web development and how to install them
properly and help you understand important aspects of your environment
such as file systems and the command line.

Your first website This module introduces you to the practicalities of
web development. You’ll gather the assets and write the code to
construct and publish a simple webpage.

Web standards This module covers the fundamentals of how the web works
at a high level — including the model used for communication, the core
technologies involved, how those technologies are created, and how a web
browser renders and displays websites to a user.

Soft skills This module provides recommendations of soft skills you can
aim to get better at while learning web development, and which
constitute good traits to have when entering the industry. They will
help immensely in developing the right attitudes for learning,
researching, and collaborating, and increase the chances of getting
hired.

See also The Frontend Developer Career Path MDN learning partner
Scrimba’s Frontend Developer Career Path teaches all you need to know to
be a competent front-end web developer, with fun interactive lessons and
challenges, knowledgeable teachers, and a supportive community. Go from
zero to landing your first front-end job! Many of the course components
are available as standalone free versions. Environment Setup Overview:
Getting started modules Next In the Environment setup module, we show
you what tools you need to do simple web development and how to install
them properly and help you understand important aspects of your
environment such as file systems and the command line.

In this article Prerequisites Tutorials Prerequisites This module
assumes no prior technical knowledge, beyond basic computer usage. You
should be able to:

Sign into your computer and connect it to the internet. Use basic system
controls such as keyboard and mouse (or other pointing devices). Install
applications. If you need to refresh yourself on such basics, we’d
recommend the following resources depending on what operating system you
are using:

Windows help and learning, Microsoft (2024) macOS User Guide, Apple
(2024) Official Ubuntu documentation, ubuntu.com (2024) Tutorials
Installing software In this article, we show you what tools you need to
do simple web development and how to install them properly. We’ll set
you up with the bare minimum of tools for now, including a text editor
and some modern web browsers.

=== Browsing the web

This article goes a little deeper into using browsers, looking at how a
web browser works, the difference between some of the common items
you’ll interact with, and how to search for information.

Code editors In this article we look at code editors in more detail,
giving you an idea of what they can do for you.

Dealing with files This article discusses some issues you should be
aware of with file systems so you can set up a sensible file structure
for your website.

=== Command line crash course

This article provides an introduction to the terminal, the essential
commands you’ll need to enter into it, how to chain commands together,
and how to add your own command line interface (CLI) tools. Installing
basic software Overview: Environment Setup Next In this article, we
discuss what software you need to do simple web development and what you
need to install now, including a code editor and some modern web
browsers.

Prerequisites: Basic familiarity with your computer operating system
(OS). Learning outcomes: +
Understand what software you need to get started. Install a code editor,
some modern browsers, and a local testing server. Explore options for
other common types of apps. In this article - Code editors - Modern web
browsers - Local web servers - Graphics editors - Version control tools
- Site deployment apps - Code editors A decent code editor is one of the
most important things for any developer to have available on their
machine. As well as being the place where you write your code, code
editors have a whole host of other functionality available. We have
dedicated an entire article to code editors later on in the series.

For now, we would recommend that you install Visual Studio Code, as it
is available across different platforms, has a great feature set and
support, and is the editor we mostly use. You should install this now to
follow along with the rest of this article.

=== Modern web browsers

Having modern web browsers available to you is essential for web
development so that you can test your websites or apps on the browsers
your visitors use to access them. You also need to keep your web
browsers up-to-date so that they support the latest web technologies and
have the latest security fixes applied.

The most common browsers you’ll come across are as follows:

==== Desktop browsers:

Chromium: Google Chrome, Opera, Brave, Microsoft Edge, Vivaldi. Gecko:
Mozilla Firefox. WebKit: Apple Safari. Mobile/alternative device
browsers: Chromium (Android): Google Chrome, Opera, Brave, Microsoft
Edge, Samsung Internet, Vivaldi. Gecko (Android): Mozilla Firefox.
WebKit (iOS): Apple Safari

== code blokovi

const button = document.querySelector("`button`");

button.addEventListener("`click`", () =++>++ ++{++ alert("`Kliknuo si
gumb!`"); });

const numbers = ++[++1, 2, 3, 4, 5++]++;

const squared = numbers.map(n =++>++ n ++*++ n); console.log(squared);
